//
// Generated file, do not edit! Created by opp_msgc 4.3 from DataFrame.msg.
//

#ifndef _DATAFRAME_M_H_
#define _DATAFRAME_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>DataFrame.msg</tt> by opp_msgc.
 * <pre>
 * message DataFrame {
 *     int flags_1;
 *     int address;
 *     int control;
 *     int information;
 *     int FCS;
 *     int flags_2;
 * }
 * </pre>
 */
class DataFrame : public ::cMessage
{
  protected:
    int flags_1_var;
    int address_var;
    int control_var;
    int information_var;
    int FCS_var;
    int flags_2_var;

  private:
    void copy(const DataFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DataFrame&);

  public:
    DataFrame(const char *name=NULL, int kind=0);
    DataFrame(const DataFrame& other);
    virtual ~DataFrame();
    DataFrame& operator=(const DataFrame& other);
    virtual DataFrame *dup() const {return new DataFrame(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getFlags_1() const;
    virtual void setFlags_1(int flags_1);
    virtual int getAddress() const;
    virtual void setAddress(int address);
    virtual int getControl() const;
    virtual void setControl(int control);
    virtual int getInformation() const;
    virtual void setInformation(int information);
    virtual int getFCS() const;
    virtual void setFCS(int FCS);
    virtual int getFlags_2() const;
    virtual void setFlags_2(int flags_2);
};

inline void doPacking(cCommBuffer *b, DataFrame& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DataFrame& obj) {obj.parsimUnpack(b);}


#endif // _DATAFRAME_M_H_
