//
// Generated file, do not edit! Created by opp_msgc 4.3 from Informacion.msg.
//

#ifndef _INFORMACION_M_H_
#define _INFORMACION_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Informacion.msg</tt> by opp_msgc.
 * <pre>
 * message Informacion {
 *     int address_dest[8];
 *     int informacion[];   
 * }
 * </pre>
 */
class Informacion : public ::cMessage
{
  protected:
    int address_dest_var[8];
    int *informacion_var; // array ptr
    unsigned int informacion_arraysize;

  private:
    void copy(const Informacion& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Informacion&);

  public:
    Informacion(const char *name=NULL, int kind=0);
    Informacion(const Informacion& other);
    virtual ~Informacion();
    Informacion& operator=(const Informacion& other);
    virtual Informacion *dup() const {return new Informacion(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getAddress_destArraySize() const;
    virtual int getAddress_dest(unsigned int k) const;
    virtual void setAddress_dest(unsigned int k, int address_dest);
    virtual void setInformacionArraySize(unsigned int size);
    virtual unsigned int getInformacionArraySize() const;
    virtual int* getInformacion();
    virtual int getInformacion(unsigned int k) const;
    virtual void setInformacion(unsigned int k, int informacion);

    //Permite crear una trama de información, destino debe ser menor que 512
    void createFrame(int destino,int* informacion, int tamInfo);
};

inline void doPacking(cCommBuffer *b, Informacion& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Informacion& obj) {obj.parsimUnpack(b);}


#endif // _INFORMACION_M_H_
